---
title: "Project-part 2"
author: "Wenjing Li"
date: "4/10/2020"
output:
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, cache=TRUE}
#loads data
data = read.csv("C:/Users/wenji/Downloads/Data/Data/Aud/Minus100_aggregated.csv",
                      header = TRUE)
vertices = read.csv("C:/Users/wenji/Downloads/Data/Data/MergeKeys.csv",
                      header = TRUE)
suppressMessages(suppressWarnings(library(e1071)))
suppressMessages(suppressWarnings(library(keras)))
suppressMessages(suppressWarnings(library(tensorflow)))
suppressMessages(suppressWarnings(library(dplyr)))
suppressMessages(suppressWarnings(library(tidyverse)))
suppressMessages(suppressWarnings(library(tidyr)))
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(class)))
suppressMessages(suppressWarnings(library(MASS)))
suppressMessages(suppressWarnings(library(rattle)))
suppressMessages(suppressWarnings(library(rpart.plot)))
suppressMessages(suppressWarnings(library(rpart)))
suppressMessages(suppressWarnings(library(randomForest)))
suppressMessages(suppressWarnings(library(gbm)))
```

## For Min100

```{r pre, warning=FALSE, cache=TRUE}
## Function to preprocess and merge the data 
data_pre = function(data,vertices,vertex_loc,freq){
  ## Rename column names appropriately 
  colnames(vertices) = c("Vertex", "MergeKey", "STG.label")
  
  ## Choose electrodes that are present only in specific regions of the STG (refer to data description document)
  loc_vertices = vertices[vertices$STG.label==vertex_loc,]
  
  ## Choose frequency levels only in a specific frequency range (Refer to data description document)
  hg_data = data[data$Freq_band==freq,]
  hg_data = data[data$Label!="NA",]
  
  ## Merge the data file with corresponding vertex locations (Refer to data description document)
  merged_data = loc_vertices%>% 
    left_join(hg_data, by = "MergeKey")
  
  ## Drop columns that are not required
  merged_data = merged_data[complete.cases(merged_data),]
  merged_data= subset(merged_data, select=-c(MergeKey,
                                             STG.label,
                                             Test_Condition,
                                             Freq_band))
  merged_data = merged_data[!merged_data$Label=="#N/A",]
  ## Convert categoricals into numeric
  merged_data = merged_data[complete.cases(merged_data),]
  merged_data$Subject_ID = as.numeric(factor(merged_data$Subject_ID))
  merged_data$Electrode_name = as.numeric(factor(merged_data$Electrode_name))
  merged_data$Label = as.numeric(factor(merged_data$Label))
  merged_data$ERSP_value = as.numeric(merged_data$ERSP_value)
  return(merged_data)
}

merged_audzero = data_pre(data, vertices, "Posterior", "hg")
### Split into train/test sets
smp_size = floor(0.70 * nrow(merged_audzero))
train_ind = sample(seq_len(nrow(merged_audzero)), size = smp_size)
min100_train = merged_audzero[train_ind, ]
min100_test = merged_audzero[-train_ind, ]

min100_train = min100_train[3:6]
min100_test = min100_test[3:6]
```

### LDA

```{r lda, warning=FALSE, cache=TRUE}
ptm <- proc.time()
lda = lda(Label ~ ., data = min100_train)
ptm_lda <- proc.time()-ptm

lda_train_pred = predict(lda, min100_train)$class
train_err = mean(lda_train_pred != min100_train$Label)
lda_test_pred = predict(lda, min100_test)$class
test_err = mean(lda_test_pred != min100_test$Label)

ptm_lda = getElement(ptm_lda, "elapsed")
```

### QDA

```{r qda, warning=FALSE, cache=TRUE}
##trains QDA model using training data
ptm <- proc.time()
qda = qda(Label ~ ., data = min100_train) 
ptm_qda <- proc.time()-ptm

##tests QDA model using testing data and training data
qda_train_pred = predict(qda, min100_train)$class
qda_test_pred = predict(qda, min100_test)$class
qda_train_err = mean(qda_train_pred != min100_train$Label)
qda_test_err = mean(qda_test_pred != min100_test$Label)

ptm_qda = getElement(ptm_qda, "elapsed")
```


### Tree

```{r tree, warning=FALSE, cache=TRUE}
set.seed(123)
tree_gini = rpart(Label ~ ., data = min100_train,
                  parms = list(split = "gini"), method = "class")
plotcp(tree_gini)
ptm <- proc.time()
set.seed(123)
tree_gini = rpart(Label ~ ., data = min100_train,
                  parms = list(split = "gini"), method = "class", cp = 0.01)
ptm_tree <- proc.time()-ptm
ptm_tree = getElement(ptm_tree, "elapsed")

fancyRpartPlot(tree_gini)
tree_test_pred = predict(tree_gini, min100_test, type = "class")
tree_test_err = mean(tree_test_pred != min100_test$Label)
tree_train_pred = predict(tree_gini, min100_train, type = "class")
tree_train_err = mean(tree_train_pred != min100_train$Label)
```

### SVM

```{r svm, warning=FALSE, cache=TRUE}
library(e1071)

#subset of the training dataset
set.seed(123)
train_1 <- as.matrix(min100_train[-4])
test_1 <- as.matrix(min100_test[-4])

train_labels = min100_train[4]
test_labels = min100_test[4]

min100_ba = which(min100_train$Label == "1")
min100_da = which(min100_train$Label == "2")
min100_ga = which(min100_train$Label == "3")
train_id_train = c(sample(min100_ba, size = trunc(300)),
             sample(min100_da, size = trunc(300)),
             sample(min100_ga, size = trunc(300)))

train_dat = data.frame(train_labels[train_id_train,], train_1[train_id_train, ])
colnames(train_dat)[1] = "labels"

test_dat = data.frame(test_labels, test_1)
colnames(test_dat)[1] = "labels"

train_dat$labels = as.factor(train_dat$labels )
test_dat$labels = as.factor(test_dat$labels )

#fit model
ptm <- proc.time()
tc = tune.control(cross=5)
tune.out =tune(svm, labels~., data= na.omit(train_dat), ranges=list(gamma = c(0.1,0.5),degree=c(1,2,3),cost=c(0.1,1,10),kernel=c("linear", "radial")))
ptm_svm <- proc.time()-ptm
ptm_svm = getElement(ptm_svm, "elapsed")

summary(tune.out)

test_pred = predict(tune.out$best.model, newdata = min100_test)
svm_test_err = mean(test_pred != min100_test$Label)
train_pred = predict(tune.out$best.model, newdata = min100_train)
svm_train_err = mean(train_pred != min100_train$Label)
```

### Summary

```{r summary, echo=FALSE, warning=FALSE, cache=TRUE}
##create table
table_error = c(train_err, test_err, ptm_lda,
                qda_train_err, qda_test_err, ptm_qda,
                tree_train_err, tree_test_err, ptm_tree,
                svm_train_err, svm_test_err, ptm_svm)
dim(table_error) = c(3,4)
colnames(table_error) = c("LDA", "QDA", "Tree(gini)", "SVM")
rownames(table_error) = c("Training Error", "Testing Error", "Computational cost")
cap = paste("*Testing and Training Evaluation for 4 Methods*")
knitr::kable(table_error, caption = cap)
```

## For Min200

```{r, echo=FALSE, warning=FALSE, cache=TRUE}
#loads data
data = read.csv("C:/Users/wenji/Downloads/Data/Data/Aud/Minus200_aggregated.csv",
                      header = TRUE)
merged_audzero = data_pre(data, vertices, "Posterior", "hg")
### Split into train/test sets
smp_size = floor(0.70 * nrow(merged_audzero))
train_ind = sample(seq_len(nrow(merged_audzero)), size = smp_size)
min100_train = merged_audzero[train_ind, ]
min100_test = merged_audzero[-train_ind, ]

min100_train = min100_train[3:6]
min100_test = min100_test[3:6]

# LDA
ptm <- proc.time()
lda = lda(Label ~ ., data = min100_train)
ptm_lda <- proc.time()-ptm

lda_train_pred = predict(lda, min100_train)$class
train_err = mean(lda_train_pred != min100_train$Label)
lda_test_pred = predict(lda, min100_test)$class
test_err = mean(lda_test_pred != min100_test$Label)

ptm_lda = getElement(ptm_lda, "elapsed")

# QDA
##trains QDA model using training data
ptm <- proc.time()
qda = qda(Label ~ ., data = min100_train) 
ptm_qda <- proc.time()-ptm

##tests QDA model using testing data and training data
qda_train_pred = predict(qda, min100_train)$class
qda_test_pred = predict(qda, min100_test)$class
qda_train_err = mean(qda_train_pred != min100_train$Label)
qda_test_err = mean(qda_test_pred != min100_test$Label)

ptm_qda = getElement(ptm_qda, "elapsed")

# TREE
#set.seed(123)
#tree_gini = rpart(Label ~ ., data = min100_train,
#                  parms = list(split = "gini"), method = "class")
#plotcp(tree_gini)
ptm <- proc.time()
set.seed(123)
tree_gini = rpart(Label ~ ., data = min100_train,
                  parms = list(split = "gini"), method = "class", cp = 0.01)
ptm_tree <- proc.time()-ptm
ptm_tree = getElement(ptm_tree, "elapsed")

fancyRpartPlot(tree_gini)
tree_test_pred = predict(tree_gini, min100_test, type = "class")
tree_test_err = mean(tree_test_pred != min100_test$Label)
tree_train_pred = predict(tree_gini, min100_train, type = "class")
tree_train_err = mean(tree_train_pred != min100_train$Label)

#SVM
set.seed(123)
train_1 <- as.matrix(min100_train[-4])
test_1 <- as.matrix(min100_test[-4])

train_labels = min100_train[4]
test_labels = min100_test[4]

min100_ba = which(min100_train$Label == "1")
min100_da = which(min100_train$Label == "2")
min100_ga = which(min100_train$Label == "3")
train_id_train = c(sample(min100_ba, size = trunc(300)),
             sample(min100_da, size = trunc(300)),
             sample(min100_ga, size = trunc(300)))

train_dat = data.frame(train_labels[train_id_train,], train_1[train_id_train, ])
colnames(train_dat)[1] = "labels"

test_dat = data.frame(test_labels, test_1)
colnames(test_dat)[1] = "labels"

train_dat$labels = as.factor(train_dat$labels )
test_dat$labels = as.factor(test_dat$labels )

#fit model
ptm <- proc.time()
tc = tune.control(cross=5)
tune.out =tune(svm, labels~., data= na.omit(train_dat), ranges=list(gamma = c(0.1,0.5),degree=c(1,2,3),cost=c(0.1,1,10),kernel=c("linear", "radial")))
ptm_svm <- proc.time()-ptm
ptm_svm = getElement(ptm_svm, "elapsed")

summary(tune.out)

test_pred = predict(tune.out$best.model, newdata = min100_test)
svm_test_err = mean(test_pred != min100_test$Label)
train_pred = predict(tune.out$best.model, newdata = min100_train)
svm_train_err = mean(train_pred != min100_train$Label)

##create table
table_error = c(train_err, test_err, ptm_lda,
                qda_train_err, qda_test_err, ptm_qda,
                tree_train_err, tree_test_err, ptm_tree,
                svm_train_err, svm_test_err, ptm_svm)
dim(table_error) = c(3,4)
colnames(table_error) = c("LDA", "QDA", "Tree(gini)", "SVM")
rownames(table_error) = c("Training Error", "Testing Error", "Computational cost")
cap = paste("*Testing and Training Evaluation for 4 Methods*")
knitr::kable(table_error, caption = cap)
```

## For Pos100

```{r, echo=FALSE, warning=FALSE, cache=TRUE}
#loads data
data = read.csv("C:/Users/wenji/Downloads/Data/Data/Aud/Pos100_aggregated.csv",
                      header = TRUE)
merged_audzero = data_pre(data, vertices, "Posterior", "hg")
### Split into train/test sets
smp_size = floor(0.70 * nrow(merged_audzero))
train_ind = sample(seq_len(nrow(merged_audzero)), size = smp_size)
min100_train = merged_audzero[train_ind, ]
min100_test = merged_audzero[-train_ind, ]

min100_train = min100_train[3:6]
min100_test = min100_test[3:6]

# LDA
ptm <- proc.time()
lda = lda(Label ~ ., data = min100_train)
ptm_lda <- proc.time()-ptm

lda_train_pred = predict(lda, min100_train)$class
train_err = mean(lda_train_pred != min100_train$Label)
lda_test_pred = predict(lda, min100_test)$class
test_err = mean(lda_test_pred != min100_test$Label)

ptm_lda = getElement(ptm_lda, "elapsed")

# QDA
##trains QDA model using training data
ptm <- proc.time()
qda = qda(Label ~ ., data = min100_train) 
ptm_qda <- proc.time()-ptm

##tests QDA model using testing data and training data
qda_train_pred = predict(qda, min100_train)$class
qda_test_pred = predict(qda, min100_test)$class
qda_train_err = mean(qda_train_pred != min100_train$Label)
qda_test_err = mean(qda_test_pred != min100_test$Label)

ptm_qda = getElement(ptm_qda, "elapsed")

# TREE
#set.seed(123)
#tree_gini = rpart(Label ~ ., data = min100_train,
#                  parms = list(split = "gini"), method = "class")
#plotcp(tree_gini)
ptm <- proc.time()
set.seed(123)
tree_gini = rpart(Label ~ ., data = min100_train,
                  parms = list(split = "gini"), method = "class", cp = 0.01)
ptm_tree <- proc.time()-ptm
ptm_tree = getElement(ptm_tree, "elapsed")

fancyRpartPlot(tree_gini)
tree_test_pred = predict(tree_gini, min100_test, type = "class")
tree_test_err = mean(tree_test_pred != min100_test$Label)
tree_train_pred = predict(tree_gini, min100_train, type = "class")
tree_train_err = mean(tree_train_pred != min100_train$Label)

#SVM
set.seed(123)
train_1 <- as.matrix(min100_train[-4])
test_1 <- as.matrix(min100_test[-4])

train_labels = min100_train[4]
test_labels = min100_test[4]

min100_ba = which(min100_train$Label == "1")
min100_da = which(min100_train$Label == "2")
min100_ga = which(min100_train$Label == "3")
train_id_train = c(sample(min100_ba, size = trunc(300)),
             sample(min100_da, size = trunc(300)),
             sample(min100_ga, size = trunc(300)))

train_dat = data.frame(train_labels[train_id_train,], train_1[train_id_train, ])
colnames(train_dat)[1] = "labels"

test_dat = data.frame(test_labels, test_1)
colnames(test_dat)[1] = "labels"

train_dat$labels = as.factor(train_dat$labels )
test_dat$labels = as.factor(test_dat$labels )

#fit model
ptm <- proc.time()
tc = tune.control(cross=5)
tune.out =tune(svm, labels~., data= na.omit(train_dat), ranges=list(gamma = c(0.1,0.5),degree=c(1,2,3),cost=c(0.1,1,10),kernel=c("linear", "radial")))
ptm_svm <- proc.time()-ptm
ptm_svm = getElement(ptm_svm, "elapsed")

summary(tune.out)

test_pred = predict(tune.out$best.model, newdata = min100_test)
svm_test_err = mean(test_pred != min100_test$Label)
train_pred = predict(tune.out$best.model, newdata = min100_train)
svm_train_err = mean(train_pred != min100_train$Label)

##create table
table_error = c(train_err, test_err, ptm_lda,
                qda_train_err, qda_test_err, ptm_qda,
                tree_train_err, tree_test_err, ptm_tree,
                svm_train_err, svm_test_err, ptm_svm)
dim(table_error) = c(3,4)
colnames(table_error) = c("LDA", "QDA", "Tree(gini)", "SVM")
rownames(table_error) = c("Training Error", "Testing Error", "Computational cost")
cap = paste("*Testing and Training Evaluation for 4 Methods*")
knitr::kable(table_error, caption = cap)
```

## For Pos200

```{r, echo=FALSE, warning=FALSE, cache=TRUE}
#loads data
data = read.csv("C:/Users/wenji/Downloads/Data/Data/Aud/Pos200_aggregated.csv",
                      header = TRUE)
merged_audzero = data_pre(data, vertices, "Posterior", "hg")
### Split into train/test sets
smp_size = floor(0.70 * nrow(merged_audzero))
train_ind = sample(seq_len(nrow(merged_audzero)), size = smp_size)
min100_train = merged_audzero[train_ind, ]
min100_test = merged_audzero[-train_ind, ]

min100_train = min100_train[3:6]
min100_test = min100_test[3:6]

# LDA
ptm <- proc.time()
lda = lda(Label ~ ., data = min100_train)
ptm_lda <- proc.time()-ptm

lda_train_pred = predict(lda, min100_train)$class
train_err = mean(lda_train_pred != min100_train$Label)
lda_test_pred = predict(lda, min100_test)$class
test_err = mean(lda_test_pred != min100_test$Label)

ptm_lda = getElement(ptm_lda, "elapsed")

# QDA
##trains QDA model using training data
ptm <- proc.time()
qda = qda(Label ~ ., data = min100_train) 
ptm_qda <- proc.time()-ptm

##tests QDA model using testing data and training data
qda_train_pred = predict(qda, min100_train)$class
qda_test_pred = predict(qda, min100_test)$class
qda_train_err = mean(qda_train_pred != min100_train$Label)
qda_test_err = mean(qda_test_pred != min100_test$Label)

ptm_qda = getElement(ptm_qda, "elapsed")

# TREE
#set.seed(123)
#tree_gini = rpart(Label ~ ., data = min100_train,
#                  parms = list(split = "gini"), method = "class")
#plotcp(tree_gini)
ptm <- proc.time()
set.seed(123)
tree_gini = rpart(Label ~ ., data = min100_train,
                  parms = list(split = "gini"), method = "class", cp = 0.01)
ptm_tree <- proc.time()-ptm
ptm_tree = getElement(ptm_tree, "elapsed")

fancyRpartPlot(tree_gini)
tree_test_pred = predict(tree_gini, min100_test, type = "class")
tree_test_err = mean(tree_test_pred != min100_test$Label)
tree_train_pred = predict(tree_gini, min100_train, type = "class")
tree_train_err = mean(tree_train_pred != min100_train$Label)

#SVM
set.seed(123)
train_1 <- as.matrix(min100_train[-4])
test_1 <- as.matrix(min100_test[-4])

train_labels = min100_train[4]
test_labels = min100_test[4]

min100_ba = which(min100_train$Label == "1")
min100_da = which(min100_train$Label == "2")
min100_ga = which(min100_train$Label == "3")
train_id_train = c(sample(min100_ba, size = trunc(300)),
             sample(min100_da, size = trunc(300)),
             sample(min100_ga, size = trunc(300)))

train_dat = data.frame(train_labels[train_id_train,], train_1[train_id_train, ])
colnames(train_dat)[1] = "labels"

test_dat = data.frame(test_labels, test_1)
colnames(test_dat)[1] = "labels"

train_dat$labels = as.factor(train_dat$labels )
test_dat$labels = as.factor(test_dat$labels )

#fit model
ptm <- proc.time()
tc = tune.control(cross=5)
tune.out =tune(svm, labels~., data= na.omit(train_dat), ranges=list(gamma = c(0.1,0.5),degree=c(1,2,3),cost=c(0.1,1,10),kernel=c("linear", "radial")))
ptm_svm <- proc.time()-ptm
ptm_svm = getElement(ptm_svm, "elapsed")

summary(tune.out)

test_pred = predict(tune.out$best.model, newdata = min100_test)
svm_test_err = mean(test_pred != min100_test$Label)
train_pred = predict(tune.out$best.model, newdata = min100_train)
svm_train_err = mean(train_pred != min100_train$Label)

##create table
table_error = c(train_err, test_err, ptm_lda,
                qda_train_err, qda_test_err, ptm_qda,
                tree_train_err, tree_test_err, ptm_tree,
                svm_train_err, svm_test_err, ptm_svm)
dim(table_error) = c(3,4)
colnames(table_error) = c("LDA", "QDA", "Tree(gini)", "SVM")
rownames(table_error) = c("Training Error", "Testing Error", "Computational cost")
cap = paste("*Testing and Training Evaluation for 4 Methods*")
knitr::kable(table_error, caption = cap)
```



## For Zero

```{r, echo=FALSE, warning=FALSE, cache=TRUE}
#loads data
data = read.csv("C:/Users/wenji/Downloads/Data/Data/Aud/Zero_aggregated.csv",
                      header = TRUE)
merged_audzero = data_pre(data, vertices, "Posterior", "hg")
### Split into train/test sets
smp_size = floor(0.70 * nrow(merged_audzero))
train_ind = sample(seq_len(nrow(merged_audzero)), size = smp_size)
min100_train = merged_audzero[train_ind, ]
min100_test = merged_audzero[-train_ind, ]

min100_train = min100_train[3:6]
min100_test = min100_test[3:6]

# LDA
ptm <- proc.time()
lda = lda(Label ~ ., data = min100_train)
ptm_lda <- proc.time()-ptm

lda_train_pred = predict(lda, min100_train)$class
train_err = mean(lda_train_pred != min100_train$Label)
lda_test_pred = predict(lda, min100_test)$class
test_err = mean(lda_test_pred != min100_test$Label)

ptm_lda = getElement(ptm_lda, "elapsed")

# QDA
##trains QDA model using training data
ptm <- proc.time()
qda = qda(Label ~ ., data = min100_train) 
ptm_qda <- proc.time()-ptm

##tests QDA model using testing data and training data
qda_train_pred = predict(qda, min100_train)$class
qda_test_pred = predict(qda, min100_test)$class
qda_train_err = mean(qda_train_pred != min100_train$Label)
qda_test_err = mean(qda_test_pred != min100_test$Label)

ptm_qda = getElement(ptm_qda, "elapsed")

# TREE
#set.seed(123)
#tree_gini = rpart(Label ~ ., data = min100_train,
#                  parms = list(split = "gini"), method = "class")
#plotcp(tree_gini)
ptm <- proc.time()
set.seed(123)
tree_gini = rpart(Label ~ ., data = min100_train,
                  parms = list(split = "gini"), method = "class", cp = 0.01)
ptm_tree <- proc.time()-ptm
ptm_tree = getElement(ptm_tree, "elapsed")

fancyRpartPlot(tree_gini)
tree_test_pred = predict(tree_gini, min100_test, type = "class")
tree_test_err = mean(tree_test_pred != min100_test$Label)
tree_train_pred = predict(tree_gini, min100_train, type = "class")
tree_train_err = mean(tree_train_pred != min100_train$Label)

#SVM
set.seed(123)
train_1 <- as.matrix(min100_train[-4])
test_1 <- as.matrix(min100_test[-4])

train_labels = min100_train[4]
test_labels = min100_test[4]

min100_ba = which(min100_train$Label == "1")
min100_da = which(min100_train$Label == "2")
min100_ga = which(min100_train$Label == "3")
train_id_train = c(sample(min100_ba, size = trunc(300)),
             sample(min100_da, size = trunc(300)),
             sample(min100_ga, size = trunc(300)))

train_dat = data.frame(train_labels[train_id_train,], train_1[train_id_train, ])
colnames(train_dat)[1] = "labels"

test_dat = data.frame(test_labels, test_1)
colnames(test_dat)[1] = "labels"

train_dat$labels = as.factor(train_dat$labels )
test_dat$labels = as.factor(test_dat$labels )

#fit model
ptm <- proc.time()
tc = tune.control(cross=5)
tune.out =tune(svm, labels~., data= na.omit(train_dat), ranges=list(gamma = c(0.1,0.5),degree=c(1,2,3),cost=c(0.1,1,10),kernel=c("linear", "radial")))
ptm_svm <- proc.time()-ptm
ptm_svm = getElement(ptm_svm, "elapsed")

summary(tune.out)

test_pred = predict(tune.out$best.model, newdata = min100_test)
svm_test_err = mean(test_pred != min100_test$Label)
train_pred = predict(tune.out$best.model, newdata = min100_train)
svm_train_err = mean(train_pred != min100_train$Label)

##create table
table_error = c(train_err, test_err, ptm_lda,
                qda_train_err, qda_test_err, ptm_qda,
                tree_train_err, tree_test_err, ptm_tree,
                svm_train_err, svm_test_err, ptm_svm)
dim(table_error) = c(3,4)
colnames(table_error) = c("LDA", "QDA", "Tree(gini)", "SVM")
rownames(table_error) = c("Training Error", "Testing Error", "Computational cost")
cap = paste("*Testing and Training Evaluation for 4 Methods*")
knitr::kable(table_error, caption = cap)
```